source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

plug "andreyorst/fzf.kak" config %{
    map global normal '<c-p>' ': fzf-mode<ret>' -docstring 'fzf mode'
    set-option global terminal 'st'
}

colorscheme tomorrow-night

map global normal '#' :comment-line<ret>

map global user -docstring 'write to file' w :write<ret>

map global user -docstring 'git mode' g ':enter-user-mode git<ret>'

declare-user-mode git
map global git -docstring 'commit' c ':git commit<ret>'
map global git -docstring 'show changes' d ':git diff<ret>'
map global git -docstring 'write and stage' w ':write<ret>:git add<ret>:git update-diff<ret>'
